module Api
    class PushNotification < ApplicationController
        protect_from_forgery with: :null_session

        def createNotification(registration_ids)
            require 'fcm'

            fcm = FCM.new("AAAAUQHhwp4:APA91bGFhhqTIvUGRGkq3gahuv4GQyRqiOEO4T92tMCz6bXSIki-zqLTFMexXV5I-qaF2eSSqz0iP3z3i997T1XAxXH6uJciLl6gp6H1PmXPOSYGLroOD1uGcKcNLM_aa_I5rcvfDf7X") # Find server_key on: your firebase console on web > tab general > web api key

            #registration_ids= [device_token] # Array of keys generated by firebase for devices 

            options = {
                    priority: "high",
                    collapse_key: "updated_score", 
                    notification: {
                        title: "Message Title", 
                        body: "Hi, Worked perfectly",
                        icon: "myicon"}
                    }

            response = fcm.send(registration_ids, options)
        end

        #def printSomething
            #puts "Hola"
        #end
    end
end